Fix SystemError when crippling a int-returning native function
Eg:
```
>>> import cripple_builtin
>>> cripple_builtin.cripple_type_slot(dict, 'mp_ass_subscript')
>>> {}[1] = 2
NotImplementedError: function has been crippled

The above exception was the direct cause of the following exception:

SystemError: _PyEval_EvalFrameDefault returned a result with an error set
```